apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-client-deploy-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-client
      tier: frontend
  template:
    metadata:
      labels:
        app: dp-client
        tier: frontend
    spec:
      containers:
      - name: container1
        image: gcr.io/cloudpark-e6cc4/dp-client:v2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: dp-client-service-v2
  labels:
    app: dp-client
    tier: frontend
spec:
  selector:
    app: dp-client
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer